### Site info:
title: Play Ground
tagline: Old dog can learn new tricks
author: Wenyu
email: wenyu.purdue@gmail.com
description: > #
  Hi, I'm an operations researcher and statistician.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site
locale: en

### Personal info and site tools info:

social:
   github: wypd
   twitter: wypd
   facebook: wypd
   email: wenyu.purdue@gmail.com

linkedin_username: wenyupurdue
github_username: wypd
disqus_shortname: wenyupurdue
favicon: "/images/avatar.png"
aboutme:  # these are shown on aboutme-sidebar.
aboutme_photo: "/images/avatar.png" # your photo.

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "one" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "

### Build settings
markdown: kramdown
kramdown:
  input: GFM
# redcarpet:
#   extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments
paginate: 5
permalink: pretty

gems:
  - jemoji
