### Site info:
title: Apprantice
tagline: Learn the hard way
author: Wenyu Wang
email: peawinter@gmail.com
description: > #
  Hi, I'm an operational researcher and statistician.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site
locale: en

### Personal info and site tools info:
# twitter_username: peawinter

social:
   github: peawinter
   twitter: peawinter
   facebook: peawinter
   email: peawinter@gmail.com

linkedin_username: peawinter
github_username: peawinter
disqus_shortname: peawinter
favicon: "/images/avatar.png"
aboutme: Hi, Im Wenyu Wang, an operational researcher and data scientist. # these are shown on aboutme-sidebar.
aboutme_photo: "/images/avatar.png" # your photo.

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "one" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "

### Build settings
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments
paginate: 5
permalink: pretty

gems:
  - jemoji
